apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: kari-panel
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/NargesKari/kari-backend:latest
          imagePullPolicy: Always
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: kari-config
            - secretRef:
                name: kari-secrets
