# Generated by Django 5.0.6 on 2026-08-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('namespaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('replicas', models.PositiveIntegerField(default=1)),
                ('cpu', models.CharField(default='250m', max_length=20)),
                ('memory', models.CharField(default='256Mi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='namespaces.namespace')),
            ],
            options={
                'unique_together': {('namespace', 'name')},
            },
        ),
    ]
